#!/bin/bash
#
# HƯỚNG DẪN TẠO 10 CÔNG TY MÔI TRƯỜNG VÀO ODOO 19
#

echo "========================================================================"
echo "🌿 HƯỚNG DẪN TẠO 10 CÔNG TY MÔI TRƯỜNG - MIỀN NAM VIỆT NAM"
echo "========================================================================"
echo ""
echo "📋 BƯỚC 1: Tạo Database (nếu chưa có)"
echo "----------------------------------------"
echo "1. Mở trình duyệt: http://localhost:10019"
echo "2. Nếu thấy form tạo database:"
echo "   - Database Name: odoo_environment"
echo "   - Login/Email: admin"
echo "   - Password: admin"
echo "   - Master Password: minhng.info"
echo "   - Nhấn 'Create Database'"
echo "3. Đợi 2-3 phút để database khởi tạo xong"
echo ""
echo "📋 BƯỚC 2: Chạy Script Tạo Công Ty"
echo "----------------------------------------"
echo "Chạy lệnh sau:"
echo ""
echo "  python3 /home/sgc/odoo-19-docker-compose/scripts/quick_create_env_companies.py"
echo ""
echo "Script sẽ hỏi:"
echo "  - Database name: nhập tên database bạn vừa tạo"
echo "  - Admin email: nhập email admin"
echo "  - Admin password: nhập password admin"
echo ""
echo "========================================================================"
echo "📚 DANH SÁCH 10 CÔNG TY SẼ ĐƯỢC TẠO:"
echo "========================================================================"
echo ""
echo "1. 🌱 Công ty TNHH Quan Trắc Môi Trường Xanh (TP.HCM)"
echo "2. 👷 Công ty CP Môi Trường và An Toàn Lao Động Miền Nam (Tiền Giang)"
echo "3. 💧 Công ty TNHH Xử Lý Nước Thải Công Nghiệp Đồng Nai (Đồng Nai)"
echo "4. 🌍 Trung Tâm Tư Vấn Môi Trường và Năng Lượng Bền Vững (Bình Dương)"
echo "5. 🌫️  Công ty TNHH Kiểm Kê Khí Nhà Kính và Tín Chỉ Carbon (Cần Thơ)"
echo "6. 🔬 Công ty CP Phân Tích Môi Trường Miền Tây (Sóc Trăng)"
echo "7. 🏭 Công ty TNHH Quan Trắc Môi Trường Lao Động An Toàn (Vũng Tàu)"
echo "8. 🚰 Công ty TNHH Giải Pháp Xử Lý Nước Thải Đô Thị (Bình Dương)"
echo "9. 📋 Công ty CP Tư Vấn và Đánh Giá Tác Động Môi Trường (Vĩnh Long)"
echo "10. 🔧 Trung Tâm Nghiên Cứu và Ứng Dụng Công Nghệ Môi Trường (An Giang)"
echo ""
echo "========================================================================"
echo "💾 BACKUP TỰ ĐỘNG ĐÃ ĐƯỢC CÀI ĐẶT:"
echo "========================================================================"
echo ""
echo "⏰ Thời gian: 4:00 sáng mỗi ngày"
echo "📁 Vị trí: /home/sgc/odoo-19-docker-compose/backups/"
echo "🗓️  Lưu trữ: 7 ngày (tự động xóa backup cũ)"
echo ""
echo "Kiểm tra cron job:"
echo "  crontab -l"
echo ""
echo "Chạy backup thủ công:"
echo "  /home/sgc/odoo-19-docker-compose/scripts/backup_odoo.sh"
echo ""
echo "========================================================================"
echo "📖 Xem thêm tài liệu chi tiết:"
echo "========================================================================"
echo ""
echo "  cat /home/sgc/odoo-19-docker-compose/ENVIRONMENTAL_COMPANIES.md"
echo "  cat /home/sgc/odoo-19-docker-compose/scripts/README.md"
echo ""
echo "========================================================================"
